dockerfile: |-
  RUN apk add --no-cache build-base yaml-dev git openssl-dev
  #RUN gem update --system
  RUN gem install bundler gem_hadar

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  bundle update --all
  bundle install --jobs=$(getconf _NPROCESSORS_ONLN)
  rake clobber test

fail_fast: true

images:
  ruby:4.0-rc-alpine: *script
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
