dockerfile: |-
  RUN apk add --no-cache build-base git

fail_fast: yes

script: &script |-
  echo -e "\e[1m"
  ruby -v
  echo -e "\e[0m"
  rm -f Gemfile.lock
  bundle install
  bundle exec rake clobber test

images:
  ruby:3.4-alpine: *script
  ruby:3.3-alpine: *script
  ruby:3.2-alpine: *script
  ruby:3.1-alpine: *script
  ruby:3.0-alpine: *script
